# Generated by Django 3.2.13 on 2023-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_in_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanted_code', models.IntegerField(blank=True, null=True)),
                ('job_family_code', models.IntegerField(blank=True, null=True)),
                ('job_sub_code', models.IntegerField(blank=True, null=True)),
                ('job_code', models.IntegerField(blank=True, null=True)),
                ('degree_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_in_one',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplyStatus',
            fields=[
                ('code', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'apply_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
            ],
            options={
                'db_table': 'careers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClickWanted',
            fields=[
                ('code', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'click_wanted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('degree_id', models.IntegerField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'degrees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'job_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobFamily',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'job_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobSubFamily',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'job_sub_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeWanted',
            fields=[
                ('code', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'like_wanted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kakao_id', models.BigIntegerField()),
                ('email', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=80)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=550, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('wanted_no', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=100)),
                ('salary_type', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('working_day', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=50)),
                ('reg_date', models.CharField(max_length=50)),
                ('close_date', models.CharField(max_length=50)),
                ('wanted_info_url', models.CharField(blank=True, max_length=200, null=True)),
                ('reper_name', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_business', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_business_cont', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_homepage', models.CharField(blank=True, max_length=150, null=True)),
                ('corp_size', models.CharField(blank=True, max_length=70, null=True)),
                ('total_emp', models.IntegerField(blank=True, null=True)),
                ('year_sales', models.IntegerField(blank=True, null=True)),
                ('corp_addr', models.CharField(blank=True, max_length=150, null=True)),
                ('job_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_type', models.CharField(blank=True, max_length=300, null=True)),
                ('apply_num', models.IntegerField(blank=True, null=True)),
                ('job_cont', models.CharField(blank=True, max_length=1000, null=True)),
                ('language_cert', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=300, null=True)),
                ('certificate', models.CharField(blank=True, max_length=300, null=True)),
                ('prefer', models.CharField(blank=True, max_length=500, null=True)),
                ('emp_process', models.CharField(blank=True, max_length=500, null=True)),
                ('apply_method', models.CharField(blank=True, max_length=300, null=True)),
                ('document', models.CharField(blank=True, max_length=300, null=True)),
                ('work_region', models.CharField(blank=True, max_length=300, null=True)),
                ('work_time', models.CharField(blank=True, max_length=300, null=True)),
                ('insurance', models.CharField(blank=True, max_length=300, null=True)),
                ('retirepay', models.CharField(blank=True, max_length=10, null=True)),
                ('etc_welfare', models.CharField(blank=True, max_length=300, null=True)),
                ('disable_con', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'wanted',
                'managed': False,
            },
        ),
    ]
